### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [mattliebetrau/project9#1]
Nice use of SCSS! There's only one thing I'd like you to fix, especially since we'll be building off this project in the future.
### Getting rid of `.DS_Store` clutter

OS X automatically generates hidden `.DS_Store` files and by default, Git will include them your commits. To get rid of this clutter in our Git repos, you can [check out this link](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).

**Comment by mattliebetrau** [comment]
Fixed! Should I close the issue?

**Comment by chrisvfritz** [comment]
:+1: Closed. :smiley:
